#!/usr/bin/env bash
#
# Build examples/sample.mp3 to the SRS §14.1 spec from raw sources.
# POD-026 (US-7 fixture; SRS §14.1 / Risk #6 closed in v1.0).
#
# Spec (locked in SRS §14.1, do not deviate):
#   ~60 s, ≤ 1 MB, mono, public-domain Spanish speech with a CC0 music
#   bed mixed in at approximately 25–35 s, bookended by speech on either
#   side so the music-detection path is exercised without ambiguous
#   boundaries.
#
# Inputs (place these in examples/sources/ before running):
#   - speech.<ext>   — the LibriVox Spanish clip (any format ffmpeg reads)
#   - music.<ext>    — the CC0 music bed
#
# Output:
#   - examples/sample.mp3                 — committed fixture
#   - examples/sources/CHECKSUMS.txt      — SHA-256 of every source +
#                                           the rendered sample.mp3
#
# Reproducibility: the script is deterministic given identical sources,
# so anyone re-running it on a different machine will produce a
# byte-identical sample.mp3 (the libmp3lame encoder is deterministic for
# fixed input + flags). Commit both the script and the resulting
# sample.mp3 so consumers don't need ffmpeg to use the fixture.
#
# Replacing the fixture: drop new sources in examples/sources/, re-run
# this script, commit the new sample.mp3 + CHECKSUMS.txt, and update
# examples/CREDITS.md with the new attribution + retrieval date. Only
# tests/fixtures/sample_tiny.md (POD-027) needs structural review after
# such a swap — exact text differs run-to-run for `tiny`.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
sources_dir="${repo_root}/examples/sources"
output="${repo_root}/examples/sample.mp3"
checksums="${sources_dir}/CHECKSUMS.txt"

speech_in=""
music_in=""
for cand in "${sources_dir}"/speech.*; do
    [[ -f "$cand" ]] || continue
    speech_in="$cand"
    break
done
for cand in "${sources_dir}"/music.*; do
    [[ -f "$cand" ]] || continue
    music_in="$cand"
    break
done

if [[ -z "$speech_in" || -z "$music_in" ]]; then
    echo "error: missing source(s) in ${sources_dir}." >&2
    echo "       expected speech.<ext> + music.<ext>" >&2
    echo "       see examples/CREDITS.md for the v1 picks." >&2
    exit 1
fi

# SRS §14.1 mix recipe — music bed *bookended* by speech (not mixed
# under it; quiet music under speech gets masked and labeled `speech`
# by the segmenter — SRS Risk #3):
#   - 0..25 s    speech.mp3[0:25]   speech alone
#   - 25..35 s   music.mp3[0:10]    music alone
#   - 35..60 s   speech.mp3[35:60]  speech resumes (skips the 25-35 s
#                                    portion of the source so wall-clock
#                                    timestamps stay natural)
# 16 kHz mono throughout — matches the CLI's canonical decode (ADR-0016).
#
# We build the intermediate WAV in /tmp to avoid leaving artifacts in
# the source tree, then encode once to MP3 with a low bitrate so the
# committed binary stays well under the 1 MB cap.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

ffmpeg -y -hide_banner -loglevel error \
    -i "$speech_in" -i "$music_in" \
    -filter_complex "
        [0:a]aformat=sample_fmts=s16:channel_layouts=mono:sample_rates=16000,atrim=0:25,asetpts=PTS-STARTPTS[s_pre];
        [1:a]aformat=sample_fmts=s16:channel_layouts=mono:sample_rates=16000,atrim=0:10,asetpts=PTS-STARTPTS[m];
        [0:a]aformat=sample_fmts=s16:channel_layouts=mono:sample_rates=16000,atrim=35:60,asetpts=PTS-STARTPTS[s_post];
        [s_pre][m][s_post]concat=n=3:v=0:a=1[out]
    " \
    -map "[out]" \
    -ac 1 -ar 16000 \
    "${tmp}/mix.wav"

# 32 kbps mono MP3 keeps a 60 s mono clip at ≈ 240 KB — well under the
# 1 MB cap from SRS §14.1.
ffmpeg -y -hide_banner -loglevel error \
    -i "${tmp}/mix.wav" \
    -ac 1 -ar 16000 -codec:a libmp3lame -b:a 32k \
    "$output"

# Recompute checksums for every source + the rendered fixture so the
# repo's record matches reality byte-for-byte. R-15 mitigation
# (PROJECT_PLAN §10.3): the sources committed under examples/sources/
# are the *exact* bytes used to build sample.mp3.
{
    echo "# Generated by examples/build_sample.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    for f in "$speech_in" "$music_in" "$output"; do
        relpath="$(python3 -c "import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))" "$f" "$repo_root")"
        sum="$(shasum -a 256 "$f" | awk '{print $1}')"
        printf "%s  %s\n" "$sum" "$relpath"
    done
} > "$checksums"

bytes=$(stat -f %z "$output" 2>/dev/null || stat -c %s "$output")
echo "wrote ${output} (${bytes} bytes)"
echo "wrote ${checksums}"
